version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2022.10
    steps: 
      - checkout
      - run: 
         command: | 
          echo "You can even have multiline commands."
                
workflows:
  build-workflow:
    jobs: 
      - build

